/**:
  ros__parameters:
    mode: "constant"          # constant | sine | stop

    # 常值模式
    constant_linear: 0.0
    constant_angular: 0.0

    # 正弦模式
    amplitude_linear: 0.5
    amplitude_angular: 0.5
    frequency: 0.2        # Hz
